In [2]:
import matlab.engine
eng = matlab.engine.start_matlab()

In [3]:
import numpy as np
test = np.array([[0., 0., 0., 0.1],
                 [0.5, 0., 0., 0.1],
                 [1.0, 0., 0., 0.1]])

print(test)

print(len(test.flatten()))


test2 = test.flatten()

test3 = test2.reshape((-1, 4))
z
print(test3)

[[0.  0.  0.  0.1]
 [0.5 0.  0.  0.1]
 [1.  0.  0.  0.1]]
12
[[0.  0.  0.  0.1]
 [0.5 0.  0.  0.1]
 [1.  0.  0.  0.1]]


In [4]:
P = 6.5293e+03
max_omega = 0.0096
test3[:,1:]

array([[0. , 0. , 0.1],
       [0. , 0. , 0.1],
       [0. , 0. , 0.1]])

In [5]:
def dimensionalise(x, **P):
    max_omega = P.pop('max_omega', 1)
    period = P.pop('period', 1)
    return np.hstack(((x[:,0]*period).reshape(-1,1), x[:,1:]*max_omega))


def batch_into_timeseries_struc(x_batch):
    x_ts = []
    for x in x_batch:
        time = x[:,0]
        data = x[:,1:] 
        matlab_time = matlab.double(time.tolist())
        matlab_data = matlab.double(data.tolist())
        x_ts += [eng.timeseries(matlab_data, matlab_time)];
    return eng.cat(1, *x_ts)

In [6]:
x_test = dimensionalise(test, period=P, max_omega=max_omega)

In [7]:
import matlab

matlab.double(x_test.tolist())

matlab.double([[0.0,0.0,0.0,0.0009599999999999999],[3264.65,0.0,0.0,0.0009599999999999999],[6529.3,0.0,0.0,0.0009599999999999999]])

In [8]:
x_test=x_test.reshape(1,*x_test.shape)

x_test

array([[[0.00000e+00, 0.00000e+00, 0.00000e+00, 9.60000e-04],
        [3.26465e+03, 0.00000e+00, 0.00000e+00, 9.60000e-04],
        [6.52930e+03, 0.00000e+00, 0.00000e+00, 9.60000e-04]]])

In [9]:
x_batch = np.tile(x_test, (30,1,1))

ipn = batch_into_timeseries_struc(x_batch)

In [100]:
# ipn = matlab.double(x_batch.tolist())
# ipn
# eng.size(ipn)
# ipn[0]
# eng.workspace['ipn'] = ipn
# eng.save('ipn.mat','ipn')
# import scipy.io

scipy.io.savemat('ipn.mat',{"xb":x_batch})

In [17]:

res = eng.batch_sim('attitude3d', ipn)
eng.save(res)

In [48]:
x = np.asarray(res)
x.shape
x=x.reshape(x.shape[-1], *x.shape[0:2])

In [49]:
x[0].shape

(654, 8)

In [57]:
x[0][:,5]

array([0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       1.57079633e+00, 1.57079633e+00, 1.57079633e+00, 1.57079633e+00,
       1.57079633e+00, 1.57079633e+00, 1.57079633e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 1.00000000e+01, 1.00000000e+01,
       1.00000000e+01, 1.00000000e+01, 1.57079633e+00, 1.57079633e+00,
       1.57079633e+00, 1.57079633e+00, 1.57079633e+00, 1.57079633e+00,
       1.57079633e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 4.79943407e-03, 4.79943407e-03, 4.79943407e-03,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
      

In [142]:
ress = scipy.io.loadmat('Ft.mat')

In [149]:
ress["Ft"].shape

(654, 8, 30)

In [17]:
eng.quit()

In [52]:
eng.linspace(0.,1.,100)

matlab.double([[0.0,0.010101010101010102,0.020202020202020204,0.030303030303030304,0.04040404040404041,0.050505050505050504,0.06060606060606061,0.0707070707070707,0.08080808080808081,0.09090909090909091,0.10101010101010101,0.1111111111111111,0.12121212121212122,0.13131313131313133,0.1414141414141414,0.15151515151515152,0.16161616161616163,0.1717171717171717,0.18181818181818182,0.1919191919191919,0.20202020202020202,0.21212121212121213,0.2222222222222222,0.23232323232323232,0.24242424242424243,0.25252525252525254,0.26262626262626265,0.2727272727272727,0.2828282828282828,0.29292929292929293,0.30303030303030304,0.31313131313131315,0.32323232323232326,0.3333333333333333,0.3434343434343434,0.35353535353535354,0.36363636363636365,0.37373737373737376,0.3838383838383838,0.3939393939393939,0.40404040404040403,0.41414141414141414,0.42424242424242425,0.43434343434343436,0.4444444444444444,0.45454545454545453,0.46464646464646464,0.47474747474747475,0.48484848484848486,0.494949494949495,0.505050505

In [55]:
eng.test(0.,1.)

matlab.double([[0.0,0.010101010101010102,0.020202020202020204,0.030303030303030304,0.04040404040404041,0.050505050505050504,0.06060606060606061,0.0707070707070707,0.08080808080808081,0.09090909090909091,0.10101010101010101,0.1111111111111111,0.12121212121212122,0.13131313131313133,0.1414141414141414,0.15151515151515152,0.16161616161616163,0.1717171717171717,0.18181818181818182,0.1919191919191919,0.20202020202020202,0.21212121212121213,0.2222222222222222,0.23232323232323232,0.24242424242424243,0.25252525252525254,0.26262626262626265,0.2727272727272727,0.2828282828282828,0.29292929292929293,0.30303030303030304,0.31313131313131315,0.32323232323232326,0.3333333333333333,0.3434343434343434,0.35353535353535354,0.36363636363636365,0.37373737373737376,0.3838383838383838,0.3939393939393939,0.40404040404040403,0.41414141414141414,0.42424242424242425,0.43434343434343436,0.4444444444444444,0.45454545454545453,0.46464646464646464,0.47474747474747475,0.48484848484848486,0.494949494949495,0.505050505